/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import controlador.Controlador;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import negocio.BD;
import negocio.Campo;
import negocio.Tabela;

/**
 *
 * @author Ruan
 */
public class JanelaTabelasDescricaoDialog extends javax.swing.JDialog {
    Controlador control;
    /**
     * Creates new form JanelaTabelasDescricaoDialog
     */
    public JanelaTabelasDescricaoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        btnCancelarTabela.setVisible(false);
        btnCancelarCampo.setVisible(false);
        try {
            control = new Controlador();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERRO de conexão com o BANCO. Procure o suporte. " + 
                        e.getMessage() );     
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO não esperado. " + 
                        e.getMessage() );
        }
    }

    JanelaTabelasDescricaoDialog(java.awt.Frame parent, boolean modal, BD bd) {
        super(parent, modal);
        initComponents();
        labelBanco.setText(bd.getNome());
        
        try {
            control = new Controlador();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERRO de conexão com o BANCO. Procure o suporte. " + 
                        e.getMessage() );     
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO não esperado. " + 
                        e.getMessage() );
        }       
        
        try {        
            control.carregarComboTabela(cmbTabela, cmbCampos, bd, jtfNomeCampo, jtfTipoCampo, jtaDescricaoCampo, jtfNomeTab, jtfTipoTab, jtaDescricao);
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar Bancos de Dados. " + 
                    erro.getMessage() + erro.getClass() );            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro não esperado ao consultar Bancos. " + 
                    erro.getMessage() + erro.getClass() );
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelDatabases5 = new java.awt.Label();
        jPanel11 = new javax.swing.JPanel();
        labelDatabases7 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        cmbTabela = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescricao = new javax.swing.JTextArea();
        btnSalvarTabela = new javax.swing.JButton();
        btnCancelarTabela = new javax.swing.JButton();
        btnEditarTabela = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfTipoTab = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeTab = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDescricaoCampo = new javax.swing.JTextArea();
        btnSalvarCampo = new javax.swing.JButton();
        btnCancelarCampo = new javax.swing.JButton();
        btnEditarCampo = new javax.swing.JButton();
        cmbCampos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeCampo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfTipoCampo = new javax.swing.JTextField();
        btnConcluirEdicoes = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dicionário da Dados");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        labelDatabases5.setBackground(new java.awt.Color(0, 102, 102));
        labelDatabases5.setForeground(new java.awt.Color(255, 255, 255));
        labelDatabases5.setText("TABELA");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(labelDatabases5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDatabases5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));

        labelDatabases7.setBackground(new java.awt.Color(0, 102, 102));
        labelDatabases7.setForeground(new java.awt.Color(255, 255, 255));
        labelDatabases7.setText("CAMPO");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(labelDatabases7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDatabases7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );

        cmbTabela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTabelaItemStateChanged(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Descricão"));

        jtaDescricao.setEditable(false);
        jtaDescricao.setColumns(20);
        jtaDescricao.setRows(5);
        jScrollPane1.setViewportView(jtaDescricao);

        btnSalvarTabela.setText("Salvar");
        btnSalvarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTabelaActionPerformed(evt);
            }
        });

        btnCancelarTabela.setText("Cancelar");
        btnCancelarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTabelaActionPerformed(evt);
            }
        });

        btnEditarTabela.setText("Editar");
        btnEditarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnCancelarTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarTabela))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarTabela)
                    .addComponent(btnCancelarTabela)
                    .addComponent(btnEditarTabela)))
        );

        jLabel2.setText("Nome: ");

        jtfTipoTab.setEditable(false);

        jLabel3.setText("Tipo: ");

        jtfNomeTab.setEditable(false);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        jtaDescricaoCampo.setEditable(false);
        jtaDescricaoCampo.setColumns(20);
        jtaDescricaoCampo.setRows(5);
        jScrollPane2.setViewportView(jtaDescricaoCampo);

        btnSalvarCampo.setText("Salvar");
        btnSalvarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCampoActionPerformed(evt);
            }
        });

        btnCancelarCampo.setText("Cancelar");
        btnCancelarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCampoActionPerformed(evt);
            }
        });

        btnEditarCampo.setText("Editar");
        btnEditarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvarCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarCampo))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCampo)
                    .addComponent(btnCancelarCampo)
                    .addComponent(btnEditarCampo)))
        );

        cmbCampos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCamposItemStateChanged(evt);
            }
        });

        jLabel4.setText("Nome: ");

        jtfNomeCampo.setEditable(false);

        jLabel5.setText("Tipo: ");

        jtfTipoCampo.setEditable(false);

        btnConcluirEdicoes.setBackground(new java.awt.Color(153, 153, 153));
        btnConcluirEdicoes.setText("CONCLUIR EDIÇÕES");
        btnConcluirEdicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirEdicoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbTabela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cmbCampos, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jtfNomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTipoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jtfNomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConcluirEdicoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cmbTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTipoTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNomeTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConcluirEdicoes)
                .addGap(5, 5, 5))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelBanco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelBanco.setText("Banco");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBanco)
                .addGap(303, 303, 303))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBanco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        //Faz com que o label apareça no centro do Jpanel
        
        labelBanco.setHorizontalAlignment(SwingConstants.CENTER); 
        
        btnSalvarTabela.setVisible(false);
        btnSalvarCampo.setVisible(false);
        btnEditarCampo.setVisible(true);
        btnEditarTabela.setVisible(true);
        btnCancelarTabela.setVisible(false);
        btnCancelarCampo.setVisible(false);
        
    }//GEN-LAST:event_formComponentShown

    private void cmbTabelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTabelaItemStateChanged
        // TODO add your handling code here:
        Tabela tab = (Tabela)cmbTabela.getSelectedItem();
        jtfNomeTab.setText(tab.getNome());
        jtfTipoTab.setText(tab.getTipo());
        jtaDescricao.setText(tab.getDescricao());
        
        try {        
            control.carregarComboCampos(cmbCampos, jtfNomeCampo, jtfTipoCampo, jtaDescricaoCampo, tab);
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar Bancos de Dados para Carregar ComboCampos. " + 
                    erro.getMessage() + erro.getClass() );            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro não esperado ao carregar ComboCampos. " + 
                    erro.getMessage() + erro.getClass() );
        }
        
        Campo campo = (Campo) cmbCampos.getSelectedItem();
        jtfNomeCampo.setText(campo.getNome());
        jtfTipoCampo.setText(campo.getTipo());
        jtaDescricaoCampo.setText(campo.getDescricao());
        
    }//GEN-LAST:event_cmbTabelaItemStateChanged

    private void cmbCamposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCamposItemStateChanged
        // TODO add your handling code here:
        Campo campo = (Campo)cmbCampos.getSelectedItem();
        jtfNomeCampo.setText(campo.getNome());
        jtfTipoCampo.setText(campo.getTipo());
        jtaDescricaoCampo.setText(campo.getDescricao());
    }//GEN-LAST:event_cmbCamposItemStateChanged

    private void btnCancelarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTabelaActionPerformed
        // TODO add your handling code here:
        Tabela tab = (Tabela)cmbTabela.getSelectedItem();
        jtaDescricao.setText(tab.getDescricao());
        jtaDescricao.setEditable(false);
        jtfNomeTab.setEditable(false);
        jtfTipoTab.setEditable(false);
    }//GEN-LAST:event_btnCancelarTabelaActionPerformed

    private void btnCancelarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCampoActionPerformed
        // TODO add your handling code here:
        jtfNomeCampo.setEditable(false);
        jtfTipoCampo.setEditable(false);
        Campo campo = (Campo)cmbCampos.getSelectedItem();
        jtaDescricaoCampo.setText(campo.getDescricao());
        jtaDescricaoCampo.setEditable(false);
        btnCancelarCampo.setVisible(false);
    }//GEN-LAST:event_btnCancelarCampoActionPerformed

    private void btnEditarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTabelaActionPerformed
        // TODO add your handling code here:
        btnCancelarTabela.setVisible(true);
        jtaDescricao.setEditable(true);
        btnSalvarTabela.setVisible(true);
        btnEditarTabela.setVisible(false);
        jtfNomeTab.setEditable(true);
        jtfTipoTab.setEditable(true);
        
    }//GEN-LAST:event_btnEditarTabelaActionPerformed

    private void btnEditarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCampoActionPerformed
        // TODO add your handling code here:
        
        jtfNomeCampo.setEditable(true);
        jtfTipoCampo.setEditable(true);
        jtaDescricaoCampo.setEditable(true);
        btnSalvarCampo.setVisible(true);
        btnEditarCampo.setVisible(false);
        btnCancelarCampo.setVisible(true);
    }//GEN-LAST:event_btnEditarCampoActionPerformed

    private void btnSalvarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTabelaActionPerformed
        // TODO add your handling code here:
        Tabela tab = (Tabela)cmbTabela.getSelectedItem();
        tab.setDescricao(jtaDescricao.getText());
        tab.setNome(jtfNomeTab.getText());
        tab.setTipo(jtfTipoTab.getText());
        
        try {
            control.alterarTabela(tab);
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar Bancos de Dados para Carregar ComboCampos. " + 
                    erro.getMessage() + erro.getClass() );            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro não esperado ao carregar ComboCampos. " + 
                    erro.getMessage() + erro.getClass() );
        }
        jtfNomeTab.setEditable(false);
        jtfTipoTab.setEditable(false);
        jtaDescricao.setEditable(false);
        btnEditarTabela.setVisible(true);
        btnSalvarTabela.setVisible(false);
        btnCancelarTabela.setVisible(false);
    }//GEN-LAST:event_btnSalvarTabelaActionPerformed

    private void btnSalvarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCampoActionPerformed
        // TODO add your handling code here:
        Campo campo = (Campo)cmbCampos.getSelectedItem();
        campo.setDescricao(jtaDescricaoCampo.getText());
        campo.setNome(jtfNomeCampo.getText());
        campo.setTipo(jtfTipoCampo.getText());
        
        try {
            control.alterarCampo(campo);
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar Bancos de Dados para Carregar ComboCampos. " + 
                    erro.getMessage() + erro.getClass() );            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro não esperado ao carregar ComboCampos. " + 
                    erro.getMessage() + erro.getClass() );
        }
        jtaDescricaoCampo.setEditable(false);
        jtfNomeCampo.setEditable(false);
        jtfTipoCampo.setEditable(false);
        btnCancelarCampo.setVisible(false);
        btnEditarCampo.setVisible(true);
        btnSalvarCampo.setVisible(false);
    }//GEN-LAST:event_btnSalvarCampoActionPerformed

    private void btnConcluirEdicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirEdicoesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnConcluirEdicoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelasDescricaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelasDescricaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelasDescricaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelasDescricaoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaTabelasDescricaoDialog dialog = new JanelaTabelasDescricaoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCampo;
    private javax.swing.JButton btnCancelarTabela;
    private javax.swing.JButton btnConcluirEdicoes;
    private javax.swing.JButton btnEditarCampo;
    private javax.swing.JButton btnEditarTabela;
    private javax.swing.JButton btnSalvarCampo;
    private javax.swing.JButton btnSalvarTabela;
    private javax.swing.JComboBox cmbCampos;
    private javax.swing.JComboBox cmbTabela;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JTextArea jtaDescricaoCampo;
    private javax.swing.JTextField jtfNomeCampo;
    private javax.swing.JTextField jtfNomeTab;
    private javax.swing.JTextField jtfTipoCampo;
    private javax.swing.JTextField jtfTipoTab;
    private javax.swing.JLabel labelBanco;
    private java.awt.Label labelDatabases5;
    private java.awt.Label labelDatabases7;
    // End of variables declaration//GEN-END:variables
}
